# Generated by Django 5.0.6 on 2024-05-24 07:31

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MataKuliah',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Ruang',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Sesi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='StatusPengumuman',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Pengumuman',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deleted', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('tanggal_kelas', models.DateTimeField()),
                ('jenis_pengumuman', models.IntegerField()),
                ('nama_dosen', models.CharField(max_length=255)),
                ('nama_asisten', models.CharField(max_length=255)),
                ('komentar', models.TextField()),
                ('nama_mata_kuliah', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pengumuman.matakuliah')),
                ('pembuat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('nama_ruang', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pengumuman.ruang')),
                ('nama_sesi', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pengumuman.sesi')),
                ('nama_status_pengumuman', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pengumuman.statuspengumuman')),
            ],
        ),
    ]
